on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: dist
          build_command: npm run build:all
      - uses: JS-DevTools/npm-publish@v3
        with:
          package: dist
          token: ${{ secrets.NPM_TOKEN }}
          registry: "https://npm.pkg.github.com"
